/**
 * @file    Style.js
 * @author  Claire Fleckney
 * @date    March 27, 2023
 * @brief   This is the Style file for controlling
 *          all styles throughout the app
 */

import { StyleSheet } from "react-native";

export default StyleSheet.create({
    backBtn: {
        backgroundColor: 'red',
        width: '75%',
        alignItems: 'center',
        margin: 5,
        padding: 2,
        borderRadius: 10,
        borderBottomColor: 'darkred',
        borderRightColor: 'darkred',
    },
    bottomContainer: {
        height: '10%',
        backgroundColor: "#303030",
        alignItems: 'center',
        justifyContent: 'center',
    },
    charSprite: {
        width: '100%',
        height: '80%',
    },
    charSpriteView: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'space-around',
    },
    combat: {
        flex: 1,
        flexDirection: 'row',
        height: '100%',
        justifyContent: 'space-evenly',
        alignItems: 'center',
    },
    combatEffect: {
        width: '30%',
        height: '60%',
    },
    combatText: {
        color: 'black',
        fontSize: 30,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    combatTextActive: {
        color: 'red',
        fontSize: 30,
        fontWeight: 'bold',
        textDecorationLine: 'underline',
        textAlign: 'center',
    },
    container: {
        flex: 1,
        flexDirection: 'column',
        backgroundColor: '#303030',
        justifyContent: 'center',
    },
    dButtonDown: {
        backgroundColor: 'transparent',
        height: 80,
        width: 80,
        margin: 1,
        borderColor: 'grey',
        borderWidth: 5,
        borderBottomLeftRadius: 80,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dButtonDownArrow: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 20,
        borderRightWidth: 20,
        borderBottomWidth: 40,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: 'grey',
        transform: [{ rotate: '-135deg'}],
    },
    dButtonLeft: {
        backgroundColor: 'transparent',
        height: 80,
        width: 80,
        margin: 1,
        borderColor: 'grey',
        borderWidth: 5,
        borderTopLeftRadius: 80,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dButtonLeftArrow: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 20,
        borderRightWidth: 20,
        borderBottomWidth: 40,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: 'grey',
        transform: [{ rotate: '-45deg'}],
    },
    dButtonRight: {
        backgroundColor: 'transparent',
        height: 80,
        width: 80,
        margin: 1,
        borderColor: 'grey',
        borderWidth: 5,
        borderBottomRightRadius: 80,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dButtonRightArrow: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 20,
        borderRightWidth: 20,
        borderBottomWidth: 40,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: 'grey',
        transform: [{ rotate: '135deg'}],
    },
    dButtonUp: {
        backgroundColor: 'transparent',
        height: 80,
        width: 80,
        margin: 1,
        borderColor: 'grey',
        borderWidth: 5,
        borderTopRightRadius: 80,
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dButtonUpArrow: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 20,
        borderRightWidth: 20,
        borderBottomWidth: 40,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: 'grey',
        transform: [{ rotate: '45deg'}],
    },
    dPadOut: {
        flexDirection: 'column',
        justifyContent: 'center',
        transform: [{ rotate: '-45deg' }],
        marginEnd: 25,
    },
    dPadIn: {
        flexDirection: 'row',
        justifyContent: 'center',
    },
    dungeonContainer: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        backgroundColor: '#303030',
    },
    fightScreen: {
        height: '100%',
        width: '100%',
        backgroundColor: 'black',
    },
    gameOver: {
        color: 'red',
        fontWeight: 'bold',
        fontSize: 50,
        textAlign: 'center',
        textAlignVertical: 'center',
    },
    header: {
        flexDirection: 'row',
        height: '20%',
        justifyContent: 'center',
        alignItems: 'center',
    },
    headerText: {
        color: 'white',
        fontSize: 30,
        fontWeight: 'bold',
        // TODO Look more into Font Families
    },
    healthBar: {
        borderWidth: 3,
        borderColor: 'black',
        borderRadius: 5,
        height: 20,
        width: '75%',
        marginBottom: 10,
        backgroundColor: 'black',
    },
    healthFill: {
        backgroundColor: 'red',
        height: '100%',
        borderRadius: 3,
    },
    instButton: {
        width: 0,
        height: 0,
        backgroundColor: 'transparent',
        borderStyle: 'solid',
        borderLeftWidth: 15,
        borderRightWidth: 15,
        borderBottomWidth: 20,
        borderLeftColor: 'transparent',
        borderRightColor: 'transparent',
        borderBottomColor: 'grey',
    },
    instPage: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#303030',
        justifyContent: 'center',
        alignItems: 'center',
    },
    instReturn: {
        backgroundColor: '#303030',
        flex: .25,
        alignItems: 'center',
    },
    instText: {
        color: 'white',
        fontSize: 20,
        textAlign: 'center',
    },
    instructions: {
        marginLeft: 15,
        marginRight: 15,
        width: '75%',
    },
    job: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
    },
    jobSelect: {
        borderWidth: 5,
        borderRadius: 15,
    },
    jobSprite: {
        aspectRatio: 1,
        height: 60,
        marginTop: 20,
        marginLeft: 10,
        marginRight: 10,
    },
    landingBtn: {
        backgroundColor: 'lightgreen',
        width: '75%',
        alignItems: 'center',
        margin: 5,
        padding: 2,
        borderRadius: 10,
        borderBottomColor: 'limegreen',
        borderRightColor: 'limegreen',
    },
    landingBtnTxt: {
        fontSize: 25,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    mapContainer: {
        flex: 1,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#303030',
    },
    mapRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    mapTile: {
        height: 42,
        width: 42,
    },
    nameInput: {
        backgroundColor: 'white',
        height: 70,
        width: '70%',
        borderRadius: 5,
        borderWidth: 2,
        borderColor: 'grey',
        padding: 10,
        fontSize: 20,
        },
    spriteLabel: {
        color: 'white',
        textAlign: 'center',
        marginTop: 10,
        marginBottom: 10,
    },
    startGame: {
        flex: .4,
        alignItems: 'center',
        justifyContent: 'flex-end',
    },
    stats: {
        flexDirection: 'row',
        justifyContent: 'center',
        margin: 0,
    },
    statContainer: {
        marginBottom: 16,
        marginHorizontal: 16,
        flexDirection: 'column',
        backgroundColor: '#303030',
        alignItems: 'center',
        alignSelf: 'center',
    },
    statHeader: {
        color: 'white',
        margin: 1,
        width: 100,
        textAlign: 'center',
        fontWeight: 'bold',
        textDecorationLine: 'underline',
        fontSize: 20,
    },
    statText: {
        color: 'white',
        margin: 1,
        width: 100,
        textAlign: 'center',
        fontSize: 15,
    },
    titleLogo: {
        resizeMode: 'contain',
        width: '90%',
    },
    topContainer: {
        height: '40%',
        backgroundColor: "#303030",
        alignItems: 'center',
        justifyContent: 'center',
    },
})
